apiVersion: v1
kind: Service
metadata:
  name: sidekiq-monitoring
  labels:
    app: sidekiq-monitoring
spec:
  type: ClusterIP
  selector:
    pod: sidekiq-monitoring
  ports:
    - name: http
      port: 80
      targetPort: 9292
      protocol: TCP
